import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { Handle, Position } from "@xyflow/react";
export const Node = ({ handles, className, ...props }) => (_jsxs(Card, { className: cn("node-container relative size-full h-auto w-sm gap-0 rounded-md p-0", className), ...props, children: [handles.target && _jsx(Handle, { position: Position.Left, type: "target" }), handles.source && _jsx(Handle, { position: Position.Right, type: "source" }), props.children] }));
export const NodeHeader = ({ className, ...props }) => (_jsx(CardHeader, { className: cn("gap-0.5 rounded-t-md border-b bg-secondary p-3!", className), ...props }));
export const NodeTitle = (props) => _jsx(CardTitle, { ...props });
export const NodeDescription = (props) => (_jsx(CardDescription, { ...props }));
export const NodeAction = (props) => _jsx(CardAction, { ...props });
export const NodeContent = ({ className, ...props }) => (_jsx(CardContent, { className: cn("p-3", className), ...props }));
export const NodeFooter = ({ className, ...props }) => (_jsx(CardFooter, { className: cn("rounded-b-md border-t bg-secondary p-3!", className), ...props }));
